version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: tjlahr
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  two:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: tjlahr
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
          at: my_workspace

      - run: echo $(cat my_workspace/echo-output)


workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
